Shortcut improvements
triggerdotdev/trigger.dev pull request #1573
Opened 2024-12-17 15:36 UTC by samejr

## New shortcut panel
![CleanShot 2024-12-17 at 15 33 55](https://github.com/user-attachments/assets/9a4ab1a4-8619-4105-adea-5268be1876a5)

## Shortcut panel accessed via the Help & Feedback popover
![CleanShot 2024-12-17 at 15 33 45](https://github.com/user-attachments/assets/8b176552-7dbf-4100-a1f8-7147f66c2d49)

## Navigate pagination left/right with 'j' and 'k' shortcut keys
![CleanShot 2024-12-17 at 15 35 03](https://github.com/user-attachments/assets/bbda7864-2233-41fb-8635-1a887f25e301)
![CleanShot 2024-12-17 at 15 35 41](https://github.com/user-attachments/assets/4ab74f24-b54e-48fb-bcb4-96505a3e4765)

2024-12-30 18:13 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Buttons.tsx
> +  }
@samejr this is a good point. If `tooltipDescription` isn't set, what do you want to happen? Is it compulsory? In which case we should only have `tooltipDescription` and remove `showTooltip`.

2024-12-30 18:14 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Buttons.tsx
> +  iconSpacing?: string;
@samejr same comment as above. Do we need both of these? Or should we just have `tooltipDescription`, which probably should just be called `tooltip`. And should probably be independent from a shortcut thinking about it, so you can have a tooltip without a shortcut.

2024-12-30 18:24 UTC, matt-aitken requested changes
Some questions about the tooltip on the button

2024-12-31 14:29 UTC, samejr commented on apps/webapp/app/components/primitives/Buttons.tsx
> +  iconSpacing?: string;
Instead of being a string, it should be a React Node

2025-01-07 22:40 UTC, jlsajfj commented
LGTM :shipit:

2025-01-08 11:58 UTC, matt-aitken approved these changes

2025-01-08 11:58 UTC, merged