Focus visible style refinements
triggerdotdev/trigger.dev pull request #1577
Opened 2024-12-18 13:46 UTC by samejr

### Focus styles are slightly more subtle
1px border instead of 2px
![CleanShot 2024-12-18 at 13 40 50@2x](https://github.com/user-attachments/assets/ccf39e92-b30c-4927-9c88-b3de69e5a41b)

### More subtle focus state for the Task input as it's auto-focused on page load
![CleanShot 2024-12-18 at 13 41 53@2x](https://github.com/user-attachments/assets/d1f38645-5b4e-472f-aac4-ac9c9dedde4a)

### Tabbing down the table now selects the rows. Enter key to select
![CleanShot 2024-12-18 at 13 44 16@2x](https://github.com/user-attachments/assets/656b4898-ed48-42f4-b48c-4121edebb619)

### Added missing focus-visible states for
- SimpleSelect
- TextLink

2024-12-30 18:04 UTC, matt-aitken requested changes
You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)

Some other comments too

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Table.tsx
> +        onClick={handleInteraction}
Does this break CMD+clicking on cells?

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Table.tsx
> -      onClick,
If you remove these from TableCellProps do you get errors when you run `pnpm run typecheck --filter webapp`. My bet is you do

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.test/route.tsx
>          </TableHeader>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.v3.usage/route.tsx
> +                          <TableHeaderCell alignment="right">Total cost</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.schedules/route.tsx
> +        <TableHeaderCell>Enabled</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.environment-variables/route.tsx
> +              <TableHeaderCell hiddenLabel>Actions</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.deployments/route.tsx
> +                    <TableHeaderCell hiddenLabel>Go to page</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.concurrency/route.tsx
> +              <TableHeaderCell alignment="right">Concurrency limit</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.apikeys/route.tsx
> +              <TableHeaderCell hiddenLabel>Actions</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam.alerts/route.tsx
> +              <TableHeaderCell hiddenLabel>Actions</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.v3.$projectParam._index/route.tsx
> +                        <TableHeaderCell hiddenLabel>Go to page</TableHeaderCell>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2024-12-30 18:04 UTC, matt-aitken commented on apps/webapp/app/components/runs/v3/TaskRunsTable.tsx
> -        <TableRow>
"You must place `<tr>` elements inside `<thead>` to contain your `<th>` cells. The correct structure is: `<thead><tr><th>Header Cell</th></tr></thead>`. [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) [2](https://www.w3.org/TR/html401/struct/tables.html)"

2025-01-21 16:04 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Table.tsx
> +  variant?: TableVariant;
Does this still need to be here?

2025-01-21 16:04 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Table.tsx
> +  variant?: TableVariant;
Does this still need to be here?

2025-01-21 16:06 UTC, matt-aitken commented on apps/webapp/app/components/primitives/Table.tsx
> +  variant?: TableVariant;
Is this needed?

2025-01-21 16:21 UTC, matt-aitken requested changes
I think we can remove the `variant` from the types in a few places.

Do the checkboxes still work no the Runs table? I just want to check that the keyboard navigation stuff hasn't broken it.

2025-01-21 16:22 UTC, samejr commented on apps/webapp/app/components/primitives/Table.tsx
> +  variant?: TableVariant;
This variant means you can pass "bright" or "dimmed" to the table to have it display nicely on bright backgrounds (like in the side inspector panels).

2025-01-21 21:11 UTC, matt-aitken approved these changes

2025-01-21 21:11 UTC, merged