feat: added git database tasks for github integration
triggerdotdev/trigger.dev pull request #204
Opened 2023-07-21 19:46 UTC by akhill10

Fixes #201 

Added following git database tasks for github integration
- [x]  [Blobs](https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28)
- [x]  [Commits](https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28)
- [x]  [References](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28)
- [x]  [Tags](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28)
- [x]  [Trees](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28)

/claim #201

2023-07-21 20:33 UTC, ericallam commented
This looks great! I'll do a proper review shortly 👍

2023-07-25 11:58 UTC, ericallam requested changes
This looks close! It would be great to get an example usage of a few of these tasks in the [github.ts](./examples/nextjs-example/src/jobs/github.ts) file as well.

2023-07-25 11:58 UTC, ericallam commented on integrations/github/src/tasks.ts
> +type ListMatchinghReferencesTask = GithubAuthenticatedTask<
Typo here, should be `ListMatchingReferencesTask`

2023-07-26 07:38 UTC, akhill10 commented
> This looks close! It would be great to get an example usage of a few of these tasks in the [github.ts](https://github.com/triggerdotdev/trigger.dev/pull/examples/nextjs-example/src/jobs/github.ts) file as well.

Sure, will do that shortly.

2023-07-29 12:50 UTC, ericallam commented
Examples look great, will be merging this in shortly 👍

2023-07-31 08:50 UTC, ericallam approved these changes

2023-07-31 08:50 UTC, merged