Adds steps to contributing guide for running some jobs locally
triggerdotdev/trigger.dev pull request #209
Opened 2023-07-24 23:36 UTC by tobihans

This PR closes #172.

It adds the sample project with event and scheduled jobs. And documents the process inside the contribution guide.

/claim #172.

2023-07-25 12:20 UTC, ericallam requested changes

2023-07-25 12:20 UTC, ericallam commented on examples/jobs-starter/package.json
> +    "@trigger.dev/nextjs": "^1.0.0-next.8",
These should point to the workspace versions, similar to how the `nextjs-example` project does. This also means you'll need to update the `tsconfig.json` of this project to use a path reference to the workspace dependencies, like so:

https://github.com/triggerdotdev/trigger.dev/blob/ba03a9ed20aef58e129e99a7acd7f540262350dc/examples/nextjs-example/tsconfig.json#L19

2023-07-25 12:20 UTC, ericallam commented on examples/jobs-starter/package.json
> +  "name": "jobs-starter",
this should be `@examples/jobs-starter`

2023-07-25 12:20 UTC, ericallam commented on CONTRIBUTING.md
> +3. Run the app:
Is this meant to run just the jobs-starter app? If so it would be great to make that clear.

2023-07-25 12:52 UTC, tobihans commented on CONTRIBUTING.md
> +3. Run the app:
Yes, that's it. I will add it. Thanks

2023-07-26 13:14 UTC, ericallam approved these changes

2023-07-26 13:27 UTC, merged