feat: encrypt values in SecretStore using an encryption key
triggerdotdev/trigger.dev pull request #240
Opened 2023-07-31 15:48 UTC by ericallam

Uses the `aes-256-gcm` symmetric algorithm to encrypt values in the SecretStore. I added a "version" field to the SecretStore, with "1" meaning the old non-encrypted value, and a new version "2" that is the encrypted variant. Updating a secret that was previously version 1 will upgrade it to version 2, but otherwise version 1 SecretStore records will remain unencrypted (well, they are encrypted at rest in AWS). Stores the IV/nonce and the tag alongside the ciphertext (the encrypted data) in the value field instead of the raw value.

2023-07-31 15:51 UTC, ericallam commented
Documentation we'll need to update once this is merged:

- [ ] The docker repo: https://github.com/triggerdotdev/docker
- [ ] The fly.io repo: https://github.com/triggerdotdev/fly.io
- [ ] Docs for fly.io: https://trigger.dev/docs/documentation/guides/deploy-to-flyio
- [ ] Docs for render.com: https://trigger.dev/docs/documentation/guides/deploy-to-render

2023-07-31 16:31 UTC, matt-aitken requested changes

2023-07-31 16:31 UTC, matt-aitken commented on apps/webapp/app/routes/api.v1.integrations.$integrationSlug.connections.$connectionId.ts
> +    return apiCors(
We should only use the `apiCors` function if we want to allow browsers to access the endpoint. It doesn't seem like we do in this situation?

2023-07-31 16:31 UTC, matt-aitken commented on apps/webapp/app/services/secrets/secretStore.server.ts
>  /** This stores secrets in the Postgres Database, in plain text. NOT recommended outside of localhost. */
We should remove this comment now that this is actually encrypted

2023-07-31 16:31 UTC, matt-aitken commented on apps/webapp/app/routes/api.v1.integrations.$integrationSlug.connections.$connectionId.ts
> +import { LoaderArgs, json } from "@remix-run/server-runtime";
What is this file used for? Just testing for now?

2023-08-01 09:08 UTC, ericallam commented on apps/webapp/app/routes/api.v1.integrations.$integrationSlug.connections.$connectionId.ts
> +import { LoaderArgs, json } from "@remix-run/server-runtime";
Yup just for being able to look at the auth but something we'll probably need eventually

2023-08-01 09:11 UTC, matt-aitken approved these changes

2023-08-01 09:11 UTC, merged