feat: added the ability to cancel scheduled Events based on the event ID
triggerdotdev/trigger.dev pull request #332
Opened 2023-08-14 14:16 UTC by Chigala

## Description
Added a function to cancel scheduled Events based on their ID. 

## Changes
- added an API endpoint `api.v1.events.$eventId.cancel.ts` to update the cancelledAt column in the EventRecord table to the time the event was cancelled. 
- add a dequeue public function in the Zodworker class that handles removal of already scheduled jobs by calling the `graphile_worker.remove_job` SQL to remove the job.  
- Added a sendEvent function in the API Client class. 

fixes #230 
/claim #230

2023-08-14 15:36 UTC, ericallam commented
Thanks for this @Chigala, will be reviewing tomorrow 👍

2023-08-14 16:22 UTC, RamK777-stack commented
@Chigala I am curious to know, how you have tested sendEvent with some future date in the deliverAt key. because the job immediately runs for me. added my doubt in https://github.com/triggerdotdev/trigger.dev/issues/230#issuecomment-1677631632. please guide me on this.

2023-08-14 22:57 UTC, Chigala commented
Hello @RamK777-stack  I believe @ericallam  has already answered you. You weren't calling the sendEvent function correctly. That's why the job was running immediately.

2023-08-16 20:30 UTC, ericallam requested changes
Looks pretty close! Can you also add a `cancelEvent` method to the `IO` class, similar to `sendEvent`:

https://github.com/triggerdotdev/trigger.dev/blob/45c1578f2abb421f37df9eba2c3fa4d9083764a7/packages/trigger-sdk/src/io.ts#L203

2023-08-16 20:30 UTC, ericallam commented on apps/webapp/app/platform/zodWorker.server.ts
> +      spec.jobKey,
Let's keep `jobKey` as optional for `addJob`

2023-08-16 20:30 UTC, ericallam commented on apps/webapp/app/routes/api.v1.events.$eventId.cancel.ts
> +//update the cancelledAt column in the eventRecord table
Can you update this to happen inside a transaction? See this file as an example: https://github.com/triggerdotdev/trigger.dev/blob/improvements/job-run-performance/apps/webapp/app/services/events/deliverEvent.server.ts

2023-08-16 20:49 UTC, Chigala commented
> Looks pretty close! Can you also add a `cancelEvent` method to the `IO` class, similar to `sendEvent`:
> 
> https://github.com/triggerdotdev/trigger.dev/blob/45c1578f2abb421f37df9eba2c3fa4d9083764a7/packages/trigger-sdk/src/io.ts#L203

Yeah, I realised I had to add that too when I saw your code snippet on Discord. I'll implement it.

2023-08-18 13:22 UTC, ericallam requested changes
A few more requested changes. One other thing is this should be updated to check to make sure the event `cancelledAt` is not set. If it is set, it should just return:

https://github.com/triggerdotdev/trigger.dev/blob/improvements/job-run-performance/apps/webapp/app/services/events/deliverEvent.server.ts

2023-08-18 13:22 UTC, ericallam commented on apps/webapp/app/services/events/cancelEvent.server.ts
> +        const event = await tx.eventRecord.findFirst({
This should be a call to `findUnique`, using the `eventId_environmentId` where:

```
tx.eventRecord.findUnique({
  where: {
    eventId_environmentId: {
      eventId: id,
      environmentId: env.id,
    }
  }
})
```

2023-08-18 13:22 UTC, ericallam commented on apps/webapp/app/services/events/cancelEvent.server.ts
> +        await workerQueue.dequeue(event.id, { tx: prisma });
I think the job_key should be `event:${event.id}` instead of just the event.id. This will need be matched by the call to enqueue.

2023-08-18 13:22 UTC, ericallam commented on apps/webapp/app/services/events/ingestSendEvent.server.ts
> +            { runAt: eventLog.deliverAt, tx, jobKey: eventLog.id }
`jobKey` should be `event:${eventLog.id}`

2023-08-21 16:49 UTC, merged