[TRI-1333] : Upgrade all packages/* and use fetch instead of node-fetch
triggerdotdev/trigger.dev pull request #542
Opened 2023-10-03 23:49 UTC by Rutam21

Closes #525 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

Type checking has been done and no errors are found.

```bash
pnpm run --filter "./packages/**" typecheck
```

![Testing](https://github.com/triggerdotdev/trigger.dev/assets/47860497/003688bb-77d7-4ebe-bddc-f6e4f7acc569)

---

## Changelog

- All the Packages are updated to use the Node v18.0.0 LTS from now on.
- Certain other dependencies are updated using `pnpm`.
- `Node-Fetch` imports and dependency are removed in all packages and `fetch` is getting used as the native function as supported by Node 18 now.

---

## Screenshots

List of all modeified files are as follows.

![File Change List](https://github.com/triggerdotdev/trigger.dev/assets/47860497/3276f323-7d34-4689-8031-31206a35245e)

2023-10-03 23:50 UTC, Rutam21 commented
@matt-aitken Please review and suggest changes, if any. Thanks

2023-10-04 08:16 UTC, ericallam commented
Have you run and tested the code still works? The easiest way to do that is to run jobs in `references/job-catalog`:

https://github.com/triggerdotdev/trigger.dev/blob/main/references/job-catalog/README.md

2023-10-04 08:27 UTC, Rutam21 commented
Hello @ericallam, So, I need to run all jobs `references/job-catalog` one by one and check if they run without any errors or running some of them is enough?
Steps for that would be as follows:

- Set .env file with the Trigger API Key
- Build the CLI
- Run each file in src
- Then run the Trigger Dev Command

Please let me know if it's the right way. Thanks.

2023-10-04 08:28 UTC, ericallam commented
No definitely don't run them all haha, I would just pick a few to run as a smoke test. The simplest is probably `events.ts`

2023-10-04 08:30 UTC, Rutam21 commented
Great, I will 3-4 files in the src and then update with the screenshots here.
So, all we are looking for now is that they run and there's no error in the terminal, right? Or do I need to look at some other paramters as well?

2023-10-04 08:33 UTC, ericallam commented
Yea considering the change, seeing successful runs should be a good enough test. And since this is a client only change, you don't even have to run the server locally if you don't want to, you could just use cloud.trigger.dev

2023-10-04 08:40 UTC, Rutam21 commented
Perfect, I will update the screenshots asap.

2023-10-04 19:54 UTC, Rutam21 commented
@ericallam I have performed the tests and updated the test results in the comments above. Please review and let me know if it looks good. Thanks.

2023-10-04 19:57 UTC, Rutam21 commented
@ericallam I have performed the tests and updated the test results in the comments above. Please review and let me know if it looks good. Thanks.

2023-10-04 21:01 UTC, Rutam21 commented
@ericallam I have performed the tests and updated the test results in the comments above. Please review and let me know if it looks good. Thanks.

2023-10-05 13:56 UTC, ericallam requested changes
Also make sure to run `pnpm run typecheck` in the root of the repo to make sure all the types still are valid.

2023-10-05 13:56 UTC, ericallam commented on packages/trigger-sdk/package.json
> +    "node": "^18.0.0"
This limits the Node version to >= 18 and < 19, which isn't what we want. I'd just do `>=18.0.0`

2023-10-06 19:35 UTC, closed without merging