[TRI-1449] Display warning message when duplicate job IDs are detected
triggerdotdev/trigger.dev pull request #699
Opened 2023-10-28 18:46 UTC by alexandredev3

Closes #691 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- Tried to define two jobs with identical IDs:
  ```ts
    client.defineJob({
      id: "same-job-id",
    });

    client.defineJob({
      id: "same-job-id",
    });
  ``` 
Got this warning message printed out to the console: `Warning: The Job "same-job-id" you're attempting to define has already been defined. Please assign a different ID to the job.`

---

## Changelog

- Added the `colorette` library; couldn't use `chalk` because it's a pure ESM package while `trigger-sdk` is being compiled to CJS.

---

💯

2023-10-30 16:19 UTC, ericallam requested changes

2023-10-30 16:19 UTC, ericallam commented on packages/trigger-sdk/src/triggerClient.ts
> +  async defineJob<
This shouldn't be an async method

2023-10-30 16:19 UTC, ericallam commented on packages/trigger-sdk/src/triggerClient.ts
> +      console.warn(
This looks good, but I think it should be something like what you have but with a bit that makes it clear the warning is from Trigger.dev: `[@trigger.dev/sdk] Warning: the Job ...`

2023-10-31 18:27 UTC, alexandredev3 commented
> This shouldn't be an async method
> This looks good, but I think it should be something like what you have but with a bit that makes it clear the warning is from `Trigger.dev: [@trigger.dev/sdk] Warning: the Job ...`

@ericallam Done!

2023-11-03 11:08 UTC, ericallam approved these changes

2023-11-03 11:10 UTC, merged