Feature/runs filtering by staus and environment
triggerdotdev/trigger.dev pull request #800
Opened 2023-12-19 07:10 UTC by Abhi1992002

Closes #520 

## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [X] The PR title follows the convention.
- [X] I ran and tested the code works

---

## Changelog

Add 2 filters , environment and status 

---

## Video

_[video]_

https://github.com/triggerdotdev/trigger.dev/assets/122007096/bc1b863e-e00d-4d43-a986-40965869fb67

💯

2023-12-19 09:34 UTC, matt-aitken requested changes
This is good but we need to use server-side filtering not client-side filtering of the runs. Client-side filtering only makes sense when you have all the data on the client, which isn't possible for us as some users have millions of runs.

2023-12-19 09:34 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
> +  }, [location.search, list.runs, setFilteredList, setselectedStatus, setSelectedEnvironment]);
This is client-side filtering which isn't the right choice for this. You can have millions of runs which we can't load on the client, so the filtering needs to happen in `RunListPresenter` by passing in the filter data and then incorporating that filter into the database query.

2023-12-19 09:34 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
> +
I think you could just use `url.toString()` here. It turns a URLSearchParams object into a valid query string: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/toString

2023-12-19 12:51 UTC, Abhi1992002 commented
sry! mistakenly commit without reading all your comments, i will add your prescribed changes and then add a new commit

2023-12-19 17:46 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
> +  const [selectedStatus, setselectedStatus] = useState<string>(ExtendedJobRunStatus.ALL);
Why do you need `useState` when you have the state in the URL?

By having both useState and the URL, you get into the tricky position where you have to sync the state between them. For example, does this work properly if you refresh the page after having set filters? My guess is it doesn't work. 

I think it would be better to just derive the selectedEnvironment from the URL, and then update the state by setting the URL which you're already doing. Then URLs can be shared between team members and no state syncing is needed.

2023-12-19 17:46 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
> +  });
You could totally remove this if you ditched the useState

2023-12-20 11:35 UTC, matt-aitken commented on apps/webapp/app/routes/_app.orgs.$organizationSlug.projects.$projectParam.runs/route.tsx
> +  const [selectedStatus, setselectedStatus] = useState<string>(ExtendedJobRunStatus.ALL);
When you select an option you get a glitchy flash, which I think is caused by this

Uploading CleanShot 2023-12-20 at 11.34.09.mp4…

2024-01-03 13:33 UTC, matt-aitken approved these changes
This is great, thanks @Abhi1992002

2024-01-03 13:37 UTC, merged