feat: Add $not to eventFilters
triggerdotdev/trigger.dev pull request #815
Opened 2023-12-27 10:21 UTC by meetwithyash

Closes #810

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Changelog

- not filter added in event filters
---

2023-12-28 16:16 UTC, matt-aitken requested changes
Could you add a false test as well?

2023-12-28 16:16 UTC, matt-aitken commented on packages/core/test/eventFilterMatches.test.ts
> +  it("should return true when payload matches an not condition", () => {
This is great! We should add a false test as well because it's relatively easy to make a code change in the future where all conditions get evaluated to true.

2023-12-29 04:22 UTC, meetwithyash commented on packages/core/test/eventFilterMatches.test.ts
> +  it("should return true when payload matches an not condition", () => {
@matt-aitken , Pushed update with other test case, Thanks!

2023-12-29 13:38 UTC, matt-aitken approved these changes

2024-01-02 15:43 UTC, merged